name: "Feature/Enhancement"
description: "Template for new features or enhancements"
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the new feature or enhancement."
      placeholder: "Enter a description of the feature."
    validations:
      - required: true

  - type: textarea
    id: why
    attributes:
      label: "Why"
      description: "Why is this feature useful?"
      placeholder: "Explain why this feature is useful."
    validations:
      - required: true

  - type: textarea
    id: changes
    attributes:
      label: "Changes"
      description: "List the main changes in this PR."
      placeholder: "- Change 1\n- Change 2\n- Change 3"
    validations:
      - required: true

  - type: textarea
    id: tests
    attributes:
      label: "Tests"
      description: "Describe how the feature was tested."
      placeholder: "Testing steps or strategy"
    validations:
      - required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - "Code compiles without errors"
        - "Feature implemented correctly"
        - "Tests added/updated"
        - "Documentation updated (if needed)"
        - "Ready for review"
    validations:
      - required: true

