name: "🐞 Bug Report"
description: Report an issue to help us improve the container
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your Linux distribution (e.g., output of `lsb_release -a`).
      placeholder: Ubuntu 24.04
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Issue Description
      description: What happened? What did you expect? How can we reproduce it?
    validations:
      required: true

  - type: textarea
    id: compose
    attributes:
      label: Docker Compose / Run Command
      description: Paste your Docker Compose file or the `docker run` command you used.
      render: yaml
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Container Logs
      description: Paste logs from `docker logs windows`.
      render: shell
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots (Optional)
      description: Add any screenshots that help explain the issue.
    validations:
      required: false

