name: "Bug Report"
description: "Create a bug report"
title: "[Bug]: "
labels: ["bug"]
body: 
  - type: input
    id: description
    attributes:
      label: "Description"
      description: "Describe the bug clearly."
      placeholder: "Describe the bug clearly."
    validations:
      - required: true

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "A short summary of the bug."
      placeholder: "A short summary of the bug."
    validations:
      - required: true    

  - type: screenshot
    id: screenshot
    attributes:
      label: "Screenshot"
      description: "Attach a screenshot of the bug (optional)."
      placeholder: "Attach a screenshot of the bug."
    validations:
      - required: false
