name: "Feature Request"
description: "Suggest a new feature."
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the feature you want."
      placeholder: "Describe the feature you want."
    validations:
      - required: true

  - type: textarea
    id: why
    attributes:
      label: "Why"
      description: "Why is this feature useful?"
      placeholder: "Explain why this feature is useful."
    validations:
      - required: true

  - type: textarea
    id: additional_notes
    attributes:
      label: "Additional Notes"
      description: "Any additional information or context."
      placeholder: "Anything else to add?"
    validations:
      - required: false
