name: "🚨 Technical Issue"
description: Report a problem with the container
body:
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: Ubuntu 24.04
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Issue Summary
      description: What happened? What should happen?
    validations:
      required: true

  - type: textarea
    id: compose
    attributes:
      label: Docker Compose / Run Command
      render: yaml
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Container Logs
      render: shell
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots (Optional)
    validations:
      required: false

